version: '3'

services:
        ovpn_webapi:
                #restart: unless-stopped
                build: ./backend
                environment:
                        - "CN_SUFFIX=vpn"
                volumes:
                        - "server:/docker/server"
                        - "ccd:/docker/ccd"
                        - "../data:/docker/data"
                ports:
                        - "9596:8080"
volumes:
        server:
        ccd:
